name: Publish to NPM and Docker

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm install

      - name: NPM CI
        run: npm ci

      - name: Publish to NPM
        run: npm publish

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t aice0927/ptc-semver-demo .
          docker push aice0927/ptc-semver-demo
